const LoginActionTypes = {
    ON_LOGIN_REQUEST_START: 'LOGIN_REQUEST_START',
    ON_LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    ON_LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
    ON_LOGIN_FORM_CLEAR: 'LOGIN_FORM_CLEAR',
    SET_USER_INFO: 'SET_USER_INFO',
    RESET_POPUP_ERROR_MSG: 'RESET_POPUP_ERROR_MSG',
    SET_LOGIN_DETAILS: 'SET_LOGIN_DETAILS',
    RESET_PASSWORD_FAIL:'RESET_PASSWORD_FAIL',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS'
};

export default LoginActionTypes;